# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "LIDC - Life in Different Colors"
description: "Videographer & Video Editor - Cinematic Visual Content"
author:      "Daniil Nuriev"
