# Build settings
markdown: kramdown
permalink: /:title

# Site settings
title: "LIDC - Life in Different Colors"
description: "Videographer & Video Editor - Cinematic Visual Content"
author: "Danil Nuriev"
url: "https://lidcvideo.com"
baseurl: ""

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache